export const TRACK_TIME_CHANGED = "TRACK_TIME_CHANGED";
export const TRACK_METADATA_UPDATED = "TRACK_METADATA_CHANGED";
export const TRACK_ENDED = "TRACK_ENDED";
export const SEEKING_STARTED = "SEEKING_STARTED";
export const SEEKING_ENDED = "SEEKING_ENDED";
export const TRACK_SEEKING = "TRACK_SEEKING";
export const TRACK_MUTE_TOGGLE = "TRACK_MUTE_TOGGLE";
export const VOLUME_UPDATED = "VOLUME_UPDATED";